import { useState } from "react";
import { createPortal } from "react-dom";
import { AlertTriangle, ArrowRight, X, Brain, HelpCircle, Server, Settings, Wifi, Search, Flame, ChevronRight, ChevronDown } from "lucide-react";

export default function TriageSummaryStoreManager({ result }) {
  const [showTrace, setShowTrace] = useState(false);
  const [showModal, setShowModal] = useState(false);

  const CAUSE_ICONS = [Server, Settings, Wifi];
  const CAUSE_COLORS = [
    { bg: "bg-blue-900/20", iconColor: "text-blue-500", bar: "bg-blue-500", pill: "text-blue-400 border-blue-900/50" },
    { bg: "bg-orange-900/20", iconColor: "text-orange-500", bar: "bg-orange-500", pill: "text-orange-400 border-orange-900/50" },
    { bg: "bg-purple-900/20", iconColor: "text-purple-500", bar: "bg-purple-500", pill: "text-purple-400 border-purple-900/50" }
  ];
  const SUBTITLES = [
    "High traffic is causing some services to slow down.",
    "Updates or changes may be affecting how things are working.",
    "Some systems are having trouble communicating."
  ];

  // Analysis Breakdown Modal
  const SummaryModal = () => createPortal(
    <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fade-in" onClick={() => setShowModal(false)}>
      <div className="bg-[#0b101d] border border-slate-800 rounded-2xl w-full max-w-2xl p-8 shadow-2xl animate-slide-up relative overflow-hidden" onClick={e => e.stopPropagation()}>
        {/* Glow effect */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-red-500/5 blur-[100px] -mr-32 -mt-32" />
        
        <div className="flex items-center justify-between mb-8 relative">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-red-950/50 flex items-center justify-center text-red-500 border border-red-900/30">
              <AlertTriangle size={24} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-slate-100">Incident Explanation</h2>
              <p className="text-xs text-slate-500 font-medium tracking-wider uppercase mt-0.5">Automated Triage Analysis</p>
            </div>
          </div>
          <button onClick={() => setShowModal(false)} className="p-2 rounded-full hover:bg-slate-800 text-slate-500 hover:text-slate-300 transition-colors">
            <X size={20} />
          </button>
        </div>
        
        <div className="space-y-6 relative">
          <div className="p-6 rounded-2xl bg-[#111827] border border-slate-800 shadow-inner">
            <div className="flex items-center gap-2 mb-4">
               <div className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />
               <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Executive Summary</span>
            </div>
            <p className="text-lg text-slate-200 leading-relaxed font-medium">
              {result.incident_summary}
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
             <div className="p-5 rounded-2xl border border-blue-900/30 bg-blue-900/5 group hover:bg-blue-900/10 transition-colors">
                <div className="text-[10px] font-bold text-blue-400 uppercase tracking-wider mb-2">Operations Impact</div>
                <div className="text-sm font-semibold text-slate-200">High impact on customer checkout flows and payment processing.</div>
             </div>
             <div className="p-5 rounded-2xl border border-purple-900/30 bg-purple-900/5 group hover:bg-purple-900/10 transition-colors">
                <div className="text-[10px] font-bold text-purple-400 uppercase tracking-wider mb-2">Evidence Confidence</div>
                <div className="text-sm font-semibold text-slate-200">Cross-referenced via telemetry, logs, and recent deployment history.</div>
             </div>
          </div>

          <div className="p-4 rounded-xl bg-amber-950/10 border border-amber-900/20 flex items-start gap-3">
            <HelpCircle size={16} className="text-amber-500 mt-0.5" />
            <p className="text-xs text-amber-200/70 leading-relaxed">
              This summary is generated by correlating multiple system signals. Review the causes below for specific mitigation steps.
            </p>
          </div>
        </div>
        
        <button 
          onClick={() => setShowModal(false)} 
          className="w-full mt-8 py-4 rounded-xl bg-slate-100 hover:bg-white text-slate-900 font-bold text-sm transition-all shadow-lg hover:shadow-white/10"
        >
          Return to Console
        </button>
      </div>
    </div>,
    document.body
  );

  return (
    <div className="flex flex-col gap-4 animate-slide-up">
      {showModal && <SummaryModal />}

      {/* Incident Summary Card */}
      <div className="rounded-xl border border-red-900/50 bg-[#150a0a] p-5 flex items-center justify-between">
        <div className="flex gap-4 items-center">
          <div className="rounded-full bg-red-950/50 p-3 text-red-500 border border-red-900/50">
            <AlertTriangle size={24} />
          </div>
          <div>
            <h2 className="text-lg font-bold text-slate-100">Incident Summary</h2>
            <p className="text-sm text-slate-300 mt-1 max-w-3xl">
              {result.incident_summary}
            </p>
          </div>
        </div>
        <button 
          onClick={() => setShowModal(true)}
          className="flex items-center gap-2 border border-red-900/50 text-red-400 bg-red-950/20 hover:bg-red-950/40 px-4 py-2 rounded-lg text-sm font-medium transition-colors shrink-0"
        >
          <Flame size={16} /> View What's Happening
        </button>
      </div>

      {/* Root Causes Card */}
      <div className="rounded-xl border border-slate-800 bg-[#0b101d] flex flex-col">
        {/* Header */}
        <div className="p-4 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-bold text-slate-100">What's Causing the Issues?</h2>
            <HelpCircle size={16} className="text-slate-500" />
          </div>
          <div className="flex items-center gap-2 text-sm text-slate-400">
            Confidence in results <HelpCircle size={14} />
          </div>
        </div>

        {/* Causes list */}
        <div className="flex flex-col">
          {result.top_causes?.map((cause, i) => {
            const Icon = CAUSE_ICONS[i % CAUSE_ICONS.length];
            const c = CAUSE_COLORS[i % CAUSE_COLORS.length];
            const pct = i === 0 ? 45 : i === 1 ? 65 : 45;
            const confidenceLevel = i === 0 ? "Medium" : i === 1 ? "High" : "Medium";
            const subtitle = SUBTITLES[i] || "Potential contributing factor based on telemetry.";

            return (
              <div key={i} className="flex items-center justify-between p-4 border-b border-slate-800">
                <div className="flex gap-4 items-center w-1/2 pr-4">
                  <div className={`p-3 rounded-lg ${c.bg} ${c.iconColor}`}>
                    <Icon size={24} />
                  </div>
                  <div>
                    <h3 className="text-sm font-bold text-slate-200">{cause}</h3>
                    <p className="text-xs text-slate-400 mt-1">{subtitle}</p>
                  </div>
                </div>

                <div className="flex items-center justify-end gap-6 w-1/2">
                  <div className="w-48 h-2 rounded-full bg-slate-800 overflow-hidden flex-shrink-0">
                    <div className={`h-full ${c.bar}`} style={{ width: `${pct}%` }} />
                  </div>
                  <div className={`text-sm font-bold ${c.iconColor} w-8`}>{pct}%</div>
                  <div className={`px-4 py-1 rounded-full border text-xs font-medium ${c.pill} w-20 text-center`}>
                    {confidenceLevel}
                  </div>
                  <ChevronRight size={16} className="text-slate-500" />
                </div>
              </div>
            );
          })}
        </div>

        {/* Footer */}
        <div className="p-4 m-4 rounded-xl border border-green-900/50 bg-green-950/10 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="p-2.5 bg-green-900/30 text-green-500 rounded-full border border-green-900/30">
              <Search size={20} />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-200">Want more details?</h3>
              <p className="text-xs text-slate-400 mt-0.5">See the technical analysis behind these insights.</p>
            </div>
          </div>
          <button
            onClick={() => setShowTrace(s => !s)}
            className="border border-green-900/50 text-green-400 px-4 py-2 rounded-lg text-sm font-medium hover:bg-green-900/20 transition-colors"
          >
            {showTrace ? "Hide Technical Details" : "View Technical Details"}
          </button>
        </div>

        {/* DeepSeek reasoning trace — collapsible */}
        {showTrace && result.reasoning_trace && (
          <div className="px-4 pb-4">
            <div className="p-4 rounded-lg text-xs leading-relaxed animate-fade-in"
              style={{
                background: "#111827", border: "1px solid #1f2937",
                color: "#94a3b8", fontFamily: "var(--font-mono)", whiteSpace: "pre-wrap"
              }}>
              <div className="flex items-center gap-2 mb-2 text-blue-400 font-bold">
                <Brain size={14} /> DeepSeek-R1 Reasoning Trace
              </div>
              {result.reasoning_trace}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
